### ISSUE TITLE
Nothing happens.

### ISSUE THREAD

**Issue by Vierdant** [inventor02/ChatToCommand#2]
I added the plugin on my test server with PlaceholdersAPI and essentials + Vault.
Didn't change anything in the config. Just restarted the server.

When I type "Hello" in the chat as it is the default word. Nothing happens.

Can I/you track this issue, please?
 The plugin sounds great and I really can use it on my network

EDIT: After messing around. It worked after I removed the placeholder %player_name% and replaced it with my IGN.
But what I wanna use a placeholder to direct the message to whoever typed the word?

**Comment by inventor02** [comment]
This is a common issue that occurs from not having the Player placeholders installed in PlaceholderAPI. You need to run `/papi ecloud download Player` as stated in the [wiki](https://www.spigotmc.org/wiki/placeholderapi-placeholders/#player-placeholders).
